service: auth-server

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  timeout: 30 # optional, in seconds, default is 6

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path:<your api path>
          method:<get, post, put, or delete>